try:
    print(x)
except NameError:
    print("An exception occurred")
